package org.planet.core.generation;

public enum ResourceType {
    Fe_HEM(0, "Fe_HEM", "Гематитовая железная руда"),
    Fe_MAG(1, "Fe_MAG", "Магнетитовая железная руда"),
    Fe_SID(2, "Fe_SID", "Сидеритовая железная руда"),
    Fe_LIM(3, "Fe_LIM", "Лимонитовая железная руда"),
    Fe_GOE(4, "Fe_GOE", "Гётитовая железная руда"),
    Fe_OOL(5, "Fe_OOL", "Оолитовая железная руда"),
    Fe_TMAG(6, "Fe_TMAG", "Титаномагнетитовая руда"),
    Fe_SAND(7, "Fe_SAND", "Железистые пески"),
    Fe_BIF(8, "Fe_BIF", "Ленточные железистые формации"),
    Fe_META(9, "Fe_META", "Метаморфизованная железная руда"),
    Mn_PYR(10, "Mn_PYR", "Пиролюзитовая марганцевая руда"),
    Mn_CARB(11, "Mn_CARB", "Карбонатная марганцевая руда"),
    Mn_FERR(12, "Mn_FERR", "Железо-марганцевая руда"),
    Cr_MASS(13, "Cr_MASS", "Массивная хромитовая руда"),
    Cr_PLAC(14, "Cr_PLAC", "Россыпная хромитовая руда"),
    Cu_CHAL(15, "Cu_CHAL", "Халькопиритовая медная руда"),
    Cu_BORN(16, "Cu_BORN", "Борнитовая медная руда"),
    Cu_CHZ(17, "Cu_CHZ", "Халькозиновая медная руда"),
    Cu_MAL(18, "Cu_MAL", "Малахитовая медная руда"),
    Cu_PORP(19, "Cu_PORP", "Порфировая медная руда"),
    Cu_SKAR(20, "Cu_SKAR", "Скарновая медная руда"),
    Cu_VMS(21, "Cu_VMS", "Колчеданная (VMS) медная руда"),
    ZnPb_SULF(22, "ZnPb_SULF", "Сульфидная цинково-свинцовая руда"),
    ZnPb_CARB(23, "ZnPb_CARB", "Карбонатная цинково-свинцовая руда"),
    ZnPb_OX(24, "ZnPb_OX", "Окисленная зона Zn/Pb"),
    ZnPb_SEDEX(25, "ZnPb_SEDEX", "Осадочная Zn/Pb (SEDEX)"),
    ZnPb_MVT(26, "ZnPb_MVT", "Zn/Pb месторождение типа MVT"),
    Ni_SULF(27, "Ni_SULF", "Сульфидная никелевая руда"),
    Ni_LAT_L(28, "Ni_LAT_L", "Латеритная никелевая (лимонит)"),
    Ni_LAT_S(29, "Ni_LAT_S", "Латеритная никелевая (сапролит)"),
    Ni_ULTRA(30, "Ni_ULTRA", "Ультраосновные никелевые породы"),
    Co_LATER(31, "Co_LATER", "Кобальтовая латеритная руда"),
    Co_SULF(32, "Co_SULF", "Сульфидная кобальтовая руда"),
    Al_BOX_L(33, "Al_BOX_L", "Боксит латеритный"),
    Al_BOX_K(34, "Al_BOX_K", "Боксит карстовый"),
    Al_NEPH(35, "Al_NEPH", "Нефелиновая руда"),
    Al_ALUN(36, "Al_ALUN", "Алунитовая руда"),
    Ti_ILM(37, "Ti_ILM", "Ильменитовая руда"),
    Ti_RUT(38, "Ti_RUT", "Рутиловая руда"),
    Ti_SAND(39, "Ti_SAND", "Титановые пески"),
    Zr_CIRC(40, "Zr_CIRC", "Цирконовая руда"),
    Sn_CASS(41, "Sn_CASS", "Касситеритовая руда"),
    Sn_PLAC(42, "Sn_PLAC", "Россыпная оловянная руда"),
    W_SCHE(43, "W_SCHE", "Шеелитовая руда"),
    W_WOLF(44, "W_WOLF", "Вольфрамитовая руда"),
    Mo_PORP(45, "Mo_PORP", "Порфировая молибденовая руда"),
    Au_QUAR(46, "Au_QUAR", "Кварцево-золотоносная руда"),
    Au_PLAC(47, "Au_PLAC", "Россыпное золото"),
    PGM_NI(48, "PGM_NI", "Платиноиды в никелевых рудах"),
    PGM_PLAC(49, "PGM_PLAC", "Россыпные платиноиды"),
    Ag_POLY(50, "Ag_POLY", "Полиметаллическая серебряная руда"),
    REE_MON(51, "REE_MON", "Монацитовая редкоземельная руда"),
    REE_BAST(52, "REE_BAST", "Бастнезитовая редкоземельная руда"),
    REE_ION(53, "REE_ION", "Ионно-адсорбционная REE глина"),
    REE_APAT(54, "REE_APAT", "Апатитовая редкоземельная руда"),
    U_URAN(55, "U_URAN", "Уранинитовая урановая руда"),
    U_SAND(56, "U_SAND", "Песчаниковая урановая руда"),
    U_PHOS(57, "U_PHOS", "Фосфатная урановая руда"),
    Th_MON(58, "Th_MON", "Ториевая руда (монацит)"),
    P_PHOS(59, "P_PHOS", "Фосфорит"),
    S_PYR(60, "S_PYR", "Пиритовая серная руда"),
    S_GAS(61, "S_GAS", "Газовая сера"),
    F_FLUOR(62, "F_FLUOR", "Флюорит"),
    B_BORAT(63, "B_BORAT", "Боратная руда"),
    Si_QUAR(64, "Si_QUAR", "Кварц высокой чистоты"),
    Si_SAND(65, "Si_SAND", "Кварцевый песок"),
    C_COAL(66, "C_COAL", "Каменный уголь"),
    C_LIGN(67, "C_LIGN", "Бурый уголь"),
    C_GRAPH(68, "C_GRAPH", "Графит"),
    Na_SALT(69, "Na_SALT", "Каменная соль"),
    K_SALT(70, "K_SALT", "Калийные соли"),
    Li_BRINE(71, "Li_BRINE", "Литиевые рассолы"),
    Mg_BRINE(72, "Mg_BRINE", "Магниевые рассолы"),
    Br_BRINE(73, "Br_BRINE", "Бромные рассолы"),
    I_BRINE(74, "I_BRINE", "Йодные рассолы"),
    Na_BRINE(75, "Na_BRINE", "Солёные рассолы"),
    Ca_BRINE(76, "Ca_BRINE", "Кальциевые рассолы"),
    H2O_FRESH(77, "H2O_FRESH", "Пресная вода"),
    H2O_SALT(78, "H2O_SALT", "Морская вода"),
    HC_OIL_L(79, "HC_OIL_L", "Лёгкая нефть"),
    HC_OIL_H(80, "HC_OIL_H", "Тяжёлая нефть"),
    HC_BITUM(81, "HC_BITUM", "Битум"),
    HC_GAS(82, "HC_GAS", "Природный газ"),
    HC_COND(83, "HC_COND", "Газовый конденсат"),
    HC_SHALE(84, "HC_SHALE", "Сланцевая нефть"),
    ATM_AIR(85, "ATM_AIR", "Атмосферный воздух"),
    ATM_CO2(86, "ATM_CO2", "Углекислый газ"),
    ATM_H2S(87, "ATM_H2S", "Сероводород"),
    ATM_NH3(88, "ATM_NH3", "Аммиачные газы"),
    GEO_HEAT(89, "GEO_HEAT", "Геотермальный флюид"),
    WIND_PWR(90, "WIND_PWR", "Ветровая энергия"),
    SOLAR_PWR(91, "SOLAR_PWR", "Солнечная энергия"),
    HYDRO_PWR(92, "HYDRO_PWR", "Гидроэнергия"),
    TIDAL_PWR(93, "TIDAL_PWR", "Приливная энергия"),
    FERTILITY(94, "FERTILITY", "Плодородие почвы (агро)"),
    FERTILITY_NAT(95, "FERTILITY_NAT", "Плодородие (естественная биота)"),
    AGRO_ZONE(96, "AGRO_ZONE", "Агроклиматическая зона"),
    IMPACT_GLASS(97, "IMPACT_GLASS", "Импактное стекло"),
    CH4_ICE_RES(98, "CH4_ICE_RES", "Лёд метана (ресурс)"),
    NH3_ICE_RES(99, "NH3_ICE_RES", "Лёд аммиака (ресурс)"),
    CO2_ICE_RES(100, "CO2_ICE_RES", "Сухой лёд (ресурс)"),
    H2O_ICE_RES(101, "H2O_ICE_RES", "Водяной лёд (ресурс)"),
    CRYO_VOLATILES(102, "CRYO_VOLATILES", "Криоволатилы (глубокие)"),
    BIO_MAT(103, "BIO_MAT", "Строительные биоматериалы");

    public final int id;
    public final String code;
    public final String name;

    ResourceType(int id, String code, String name) {
        this.id = id;
        this.code = code;
        this.name = name;
    }
}
